name = "Free Fall Off The Ramp"
prefix = "ffr"
mainprefix = "z"

[properties]
author = "Ampersand"
url = "https://github.com/ampersand38/free-fall-off-the-ramp"

[files]
include = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "meta.cpp"
]
exclude = [
    ".vscode",
    "*.sqfc",
]
