name = "Free Fall Off The Ramp"
prefix = "ffr"
mainprefix = "z"

[properties]
author = "Ampersand"
url = "https://github.com/ampersand38/free-fall-off-the-ramp"

[files]
include = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "meta.cpp"
]
exclude = [
    ".vscode",
    "*.sqfc",
]

[hemtt.launch.default]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]
workshop = [
    "450814997", # CBA_A3
    "333310405", # enhanced movement
    "843577117", # RHS USAF
    "463939057", # ACE3
    "1944099353" # bf vehichles a400m
]
mission = "editor_para.Stratis" # Path to the mission to launch
